### ISSUE TITLE
vcfanno version deprecated

### ISSUE THREAD

**Issue by brainstorm** [sigven/pcgr#10]
This is to track the following issue (old vcfanno version on PCGR having issues parsing some VCF files):

https://github.com/brentp/irelate/issues/2

Since I'm not sure a fix has been released for it yet on PCGR source and docker images?

Heads up for @ohofmann who will run some data through it soon and might run into this again...

**Comment by sigven** [comment]
Hi,

Sorry for the long delay with this issue (primarily due to work on additional updates/changes). Try out the [latest release (0.4.2.1)](https://github.com/sigven/pcgr/releases/tag/0.4.2.1), it has vcfanno updated (0.2.8), both in Docker images and source.
Let me know if that works better.

regards,
Sigve

**Comment by brainstorm** [comment]
Thanks much @sigven, I'll give it a spin and let you know next time Oliver needs it.
