### ISSUE TITLE
Tumor suppressor list

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/pcgr#106]
Hi Sigve,

Just wondering how you put together a list of tumor suppressors and oncogenes?

A coding variant in EHD2 has downgraded from TIER3 to TIER4 compared to PCGR 0.8.0:

<img width="911" alt="pcgr080" src="https://user-images.githubusercontent.com/1575412/74406162-3c1d1a80-4e72-11ea-8269-861eaaba5311.png">

<img width="922" alt="pcgrdev" src="https://user-images.githubusercontent.com/1575412/74406168-3fb0a180-4e72-11ea-849c-3f9b3e40ec25.png">

And I suspect it's because EHD2 was removed from a tumor suppressors or oncogenes list, but trying to figure out how can I confirm it. The gene is still listed in cancermine as a tumor suppressor though.

Vlad

**Comment by sigven** [comment]
Hi Vlad,

You are correct that I use the [CancerMine]() resource as the source for proto-oncogenes and tumor suppressors. This is the most up-to-date resource, but one must clearly take into account that text mining contains some inherent noise. I therefore do not include all the entries in CancerMine, but rather have put a restriction on the genes that are listed, meaning that they need a minimum number of citations in order to make it into the list used in PCGR. And I have also resolved some cases in which some obvious tumor suppressors have some signal (noise) from the other category (oncogenes), say e.g. a citation ratio of 250 to 6, for these the oncogene annotations is skipped (and vice versa). Perhaps one may add some level of confidence in the future, and that links to underlying literature supporting an oncogenic/tumor suppresive role can be listed even for those (TIER 4) that do not have sufficient  support. Knowing what is _sufficient_ is also challenging, so far this is performed in an ad-hoc manner as an attempt to remove the most obvious noise.

If I manage to make the data bundle generation more available to the community, it would be easier for you guys to pick this up, I realize this should be prioritised (but there is plenty of other things coming up too! :-))

Sigve

**Comment by vladsaveliev** [comment]
That's awesome and really helpful. Adding restriction on the number of citations totally makes sense.

Actually we have our own [list of "cancer" genes](https://github.com/umccr/workflows#gene-lists) in UMCCR compiled from various lists and panels, and as part of building it, we annotate genes as tumor suppressors or oncogenes, grabbing information from canermine, [NGC](http://ncg.kcl.ac.uk/cancer_genes.php#known), COSMIC cencus, and [TSGene](https://bioinfo.uth.edu/TSGene/). We then use the tumor suppressor and oncogene labels to prioritize SVs and CNVs.

For cancermine, we as well use a threshold on the number of citations, specifically 3: https://github.com/umccr/workflows/blob/master/genes/cancer_genes/make_umccr_cancer_genes.Rmd#L89 So I guess it's similar to what you are doing. Though thinking that it would be great to sync PCGR, and other parts of our pipeline in terms of lists of genes and hotspots, so sharing the code that builds the PCGR data bundles would be really fantastic!

Vlad

**Comment by sigven** [comment]
Thanks alot for your input, Vlad. I've considered also to include the other resources you point to (which partly was also some of the sources I used initially). An overall goal for PCGR/CPSR is to avoid resources that are associated with licensing, since this will complicate things when the databundle is distributed with the program (at least that is my impression, although licensing issues are not something I know so much about). 

I also thought that combining for instances annotations from CancerMine, CGC and TSGene could make up a nice foundation to arrive at the most confident oncogenes/tumor suppressor, but having played a bit with this, these sources are quite complementary (this is also reported in the [Nature Methods paper of CancerMine](https://www.nature.com/articles/s41592-019-0422-y/figures/2)). This holds even when omitting annotations in CancerMine with a limited number of citations. I've noticed a number of studies that use the CGC list as the "gold standard" of cancer genes, but my take is that there quite a number of candidates in e.g. CancerMine that is reported heavily in the literature, but with no record yet in the manual curation effort of CGC (for reasons I do not know). And vice versa, apparently some genes in CGC with no citations in the biomedical literature. So to me, it seems that no source is more "trustworthy" than others, but rather that they are quite complementary. 

The aspects of both CGC and CancerMine that makes them most attractive is that they annotate the mode of action (suppressor/oncogene) in the context of a particular tumor type. This dimension is not yet part of PCGR, but could be a nice extension.

Sigve

**Comment by vladsaveliev** [comment]
That's interesting! That's what I also noticed - that the resources are to a large part complimentary. So I guess the way to go is to merge all lists and apply a threshold on the total number of citations. But might be a rabbit hole though.

Using labels in the context of tumor type totally makes sense. Though we are still not passing the tumor type down the workflow internally. Might start doing it at some point in the future. 

Vlad
