### ISSUE TITLE
Read Depth and Zygosity

### ISSUE THREAD

**Issue by ngslabex** [sigven/pcgr#108]
is it possible to see read depths and genotype in the variant browser?

**Comment by sigven** [comment]
Hi @ngslabex,

Short answer: Yes! See the variant browser in the [example report](http://folk.uio.no/sigven/tumor_sample.BRCA.pcgr_acmg.grch37.html)

Long answer:
Zygosity is not really a common figure to report for somatic variants (for germline variants this is another story). The allelic fraction for each variant is however a common measure to report. To have read depth and allelic fraction present in the variant browser, ensure you have performed the following:

1. Include read depth and allelic fraction as individual INFO tags in your VCF, e.g. as _TDP_ and _TVAF_ (look carefully at how the this is done in the [example.vcf.gz](https://github.com/sigven/pcgr/blob/master/examples/tumor_sample.BRCA.vcf.gz)). 
2. Configure your run in the TOML file by setting the _tumor_dp_tag_ and _tumor_af_tag_ according to how they are defined your VCF, i.e.:
`tumor_dp_tag = "TDP"`
`tumor_af_tag = "TVAF"`

See also the [configuration file for the example](https://github.com/sigven/pcgr/blob/master/examples/examples_BRCA.toml).

In an ideal world, PCGR should be able to pull this information from any VCF. However, considering that there is no standard way to report this in a VCF (different variant callers use very different ways to report this), handling this automatically is very challenging. Therefore, in order to have this in place, we require that the user is able to format the input VCF according to the above requirements. Meaning that you must be able to post-process your VCF to a certain extent. Bottom line, adjusting your VCF according to the example VCF's should help you out, I believe.

best,
Sigve
