### ISSUE TITLE
R character strings are limited to 2^31-1 bytes

### ISSUE THREAD

**Issue by YingYa** [sigven/pcgr#118]
Hi，

There is a error when writing JSON file.

2020-11-03 10:49:55 [INFO] Writing JSON file (.json) with report contents
Error in collapse(tmp, inner = FALSE, indent = indent) :
  R character strings are limited to 2^31-1 bytes
Calls: <Anonymous> ... .local -> vapply -> FUN -> FUN -> .local -> collapse
Execution halted

**Comment by sigven** [comment]
Hi,
Thanks for reporting. Can you share your input VCF, so I can understand why it fails? 

Regards,
Sigve

**Comment by YingYa** [comment]
Hi Sigve,

Thank you for your prompt reply. I am using pcgr-0.9.0.2 installed by conda with following parameters:
pcgr.py --pcgr_dir /path/to/pcgr-0.9.0.2 --input_vcf /path/to/test.MuTect2.PASS.vcf.gz --input_cna /path/to/test.CNVkit_cbs.seg.tsv --force_overwrite  --no-docker --output_dir /path/to/report.test.single.CRC --genome_assembly grch38 --conf /path/to/pcgr_conf.test.single.toml --tumor_site 9 --no_vcf_validate --include_trials --assay WGS --estimate_signatures --estimate_msi_status --estimate_tmb --sample_id test.single.CRC --tumor_only

the  Here are the SNV and CNV files:
https://drive.google.com/file/d/1-jiaW0g54xumFrREFiiIPOQ-9ESRuzUq/view?usp=sharing
https://drive.google.com/file/d/1zEhQ2oXZqGHCVs1-xTxw6Ijczv9BPiNg/view?usp=sharing

Regards,
Yingya

**Comment by sigven** [comment]
Testing now, seems like a memory issue in R, given that the input is fairly large. Will get back to you once I figure out how it should handled properly.

**Comment by YingYa** [comment]
Hi Sigve,

Have the bug been fixed?

Regards,
Yingya

**Comment by sigven** [comment]
Hi @YingYa,

Sorry for the delay. I am afraid not, analysis of WGS tumor-only runs need an improved and less memory-intensive implementation than what is currently available. Since the focus of PCGR is by far on the protein-coding contents, I would recommend (as a temporary solution) that you basically intersect your raw input VCF against an exome target file (BED), and then feed this into PCGR. This is clearly not optimal, but may work as a preliminary way to have your variants analyzed. I will try to test this myself as well, when I am back at work next week.

Again, sorry for the delay in feedback.

kind regards,
Sigve

**Comment by sigven** [comment]
@YingYa, think I've figured out a way to make it work, essentially leaving out the immensely huge unfiltered variant set in the JSON file. Will do a bit more testing and push it for the next release.

Sigve

**Comment by sigven** [comment]
Fixed in v0.9.2
