### ISSUE TITLE
HLA contigs in vcf files' headers generate error

### ISSUE THREAD

**Issue by V-Catherine** [sigven/pcgr#124]
Hello,
I got errors while running pcgr because of the HLA contigs in the mutect vcf files' headers: 
"According to the VCF specification, the VCF file (test.vcf.gz) is NOT valid: ERROR: Line 2903: Metadata ID contains a character different from alphanumeric, dot, underscore and dash. etc..."
These headers (~525 lines) are by default when working on hg38 and look like:
##contig=<ID=HLA-DRB1\*15:01:01:04,length=11056>
So would it be possible to add the star in the authorized characters ?
Thanks
Catherine

**Comment by sigven** [comment]
Hi Catherine,
I do not want to alter the criteria for success/fail in VCF validator. I suggest you do the following:

1) If you believe the reminder of your VCF adheres correctly to the VCF format, simply turn on the `--vcf_no_validate` option when you run PCGR, to turn off the vcf-validation step altogether.

2) If you think the HLA contig format is commonly formatted like this in VCF files, I would suggest that you file an issue in the [VCF-validator repository](https://github.com/EBIvariation/vcf-validator) to get their opinion on the  matter.

regards,
Sigve

**Comment by V-Catherine** [comment]
OK. Thanks for your suggestions :-)

**Comment by ttbek** [comment]
Hi Sigve, 

  I understand that VCF validation may be beyond the scope of your project, but I would like to point out that the opinion of VCF-validator's author[s] has no bearing on whether or not it is a valid VCF other than any influence they may have in writing the specifications.  The written specifications are the final word on the validity of a VCF, regardless of whatever some particular implementation does incorrectly.  You can find the current version here: https://samtools.github.io/hts-specs/VCFv4.3.pdf  There is a v4.4 draft available as well if you want to check out the future version of the spec.  

I will quote the relevant portion here: 

```
"Contig names follow the same rules as the SAM format’s reference sequence names: they may contain any printable
ASCII characters in the range [!-~] apart from ‘\ , "‘’ () [] {} <>’ and may not start with ‘*’ or ‘=’. Thus they
match the following regular expression:
[0-9A-Za-z!#$%&+./:;?@^_|~-][0-9A-Za-z!#$%&*+./:;=?@^_|~-]*
In particular, excluding commas facilitates parsing ##contig lines, and excluding the characters ‘<>[]’ and initial ‘*’
avoids clashes with symbolic alleles. The contig names must not use a reserved symbolic allele name."
```
The star is not at the start of the contig name, so it is a perfectly valid contig name.  

Hopefully vcf-validator is willing to make the correction, but if not, then I would suggest that you seek a validation method that conforms to the spec.

**Comment by sigven** [comment]
Hi @ttbek,

Thanks for looking more into this matter. You are correct that vcf validation is not at the core of my tool, in the sense that I am rather relying upon another tool for this. Before I make any judgement as to the correctness of vcf-validator, I will look into whether I an updated version of vcf-validator (than the one being currently in use in PCGR) might resolve this issue. 

My experience is either way that a lot of users turn off the VCF validation, basically since most VCF files out there do not follow the specifications in a strict manner. Perhaps a more "relaxed" validation would make more sense, but really do not want to re-invent anything there.

Thanks again for helping out here, much appreciated!

kind regards,
Sigve

**Comment by sigven** [comment]
@ttbek: minor update. We have played a bit with [bcftools](https://samtools.github.io/bcftools/bcftools.html). Overall, we think that should act as a valid substitute for vcf-validator, providing a small test to check that the input is indeed a VCF file. Since many users are either way turning of vcf-validation, we hope things will get simpler with a new validation scheme in place.
