### ISSUE TITLE
TMB from panels

### ISSUE THREAD

**Issue by kokyriakidis** [sigven/pcgr#131]
Hi,

I wanted to ask if PCGR TMB calculations from panels use some sophisticated statistical calculations to derive WES level TMB approximations.

KK

**Comment by sigven** [comment]
Hi,

Make sure you set the `--target_size_mb` option (i.e. size of (coding) target region in megabases) correctly when you run PCGR on panels. This will normalize the TMB measure accordingly, so that the TMB estimate is truly comparable across different assays (WES, small panels etc). You can choose to have your TMB measured as all coding SNVs/InDels (including silent mutations) pr. megabase, as done in [Chalmers et al.](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-017-0424-2), or use the count of non-synonymous mutations only as the numerator in the TMB estimate (option `--tmb_algorithm`)

regards,
Sigve
