### ISSUE TITLE
How can I extract EXON and INRON information from vcf INFO tag annotated by the vep with the --numbers parameter?

### ISSUE THREAD

**Issue by QifengSun** [sigven/pcgr#134]
the new version stop used the **toml** configuration file, and have no parameter in the command line to set the custom_tags.
How can I extract **EXON** and **INRON** information from vcf **INFO** tag annotated by the **vep** with the **--numbers** parameter.

[custom_tags]
\## list VCF info tags that should be present in JSON and TSV output
\## tags should be comma separated, i.e. custom_tags = "MUTECT2_FILTER,STRELKA_FILTER"
**custom_tags** = "EXON,INTRON"

**Comment by sigven** [comment]
Hi @QifengSun ,

If you take a look at the [latest CHANGELOG](https://pcgr.readthedocs.io/en/latest/CHANGELOG.html#june-30th-2021), there is now a new option `--preserved_info_tags` which replaces the previous`custom_tags` section of the TOML file. If there are specific INFO tags you want to keep in your output, you specify them here (i.e. `--preserved_info_tags EXON,INTRON`). Since these tags come from VEP (and will thus also be generated by PCGR), I might also add them (EXON, INTRON) to the default columns of the output TSV in the upcoming release, if you think this is convenient. 

regards,
Sigve

**Comment by QifengSun** [comment]
Thanks for replying so quickly!
![image](https://user-images.githubusercontent.com/18737212/127245070-574fa0a8-9217-4b89-99d6-b871854a3e2a.png)
the **INFO** tags ### EXON and the **INTRON** was generated by the **VEP --numbers** parameter  NOT in the _original input vcf file._ So it doesn't work use the **--preserved_info_tags EXON,INTRON**. The INFO tags EXON,INTRON show the EXON position the variance occurs out of the total EXONs, like "7/10" . So it it very convenient. and I hope the next version can add the --custom_tags parameters for the user, it it very convenient to customerize the local analysis work flow.
regards,
Qifeng

**Comment by sigven** [comment]
Addressed this issue in [#issue 135](https://github.com/sigven/pcgr/issues/135)
