### ISSUE TITLE
I geetinng this particular issue while running in grch 37

### ISSUE THREAD

**Issue by mano2991** [sigven/pcgr#137]
Quitting from lines 121-149 (./acmg/tier2_acmg.Rmd) 
Quitting from lines NA-158 (./acmg/tier2_acmg.Rmd) 
Error in list(crosstalk::filter_select("EVIDENCE_LEVEL", "Evidence level",  : 
  argument 4 is empty
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> <Anonymous>
Execution halted
I'm facing this issue while I'm using grch37 if I use grch 38 as the reference in PCGR it's not showing any error

**Comment by sigven** [comment]
Hi @mano2991,
Thanks a lot for reporting this! Could you share your input (VCF) with me, in order for me to reproduce the error? I also need your parameter settings (and PCGR version + bundle in use).

kind regards,
Sigve

**Comment by mano2991** [comment]
Hi, @sigven I have shared with you the VCF file https://drive.google.com/drive/folders/1Dz3oVuxXcCx37VMbgByKIZ1NiaFTaqas?usp=sharing.  
i have used pcgr 0.8.3 
python pcgr-0.8.3/pcgr.py  Out_put/Test grch37 pcgr-0.8.3/conf/pcgr.toml 008108943_37 --input_vcf VCF/008108943.vcf --no_vcf_validate

**Comment by sigven** [comment]
Hi @mano2991,

Before I do any bug hunting with your query, I strongly recommend that you try to check whether the error persists for the latest PCGR release (0.9.2). The software is subject to continuous improvements, and using the latest release is generally recommended. Ok?

kind regards,
Sigve

**Comment by mano2991** [comment]
@sigven thanks for suggesting, I ran in the latest version also and I got the same error with pcgr 0.9.2 python ../pcgr-0.9.2/pcgr.py --pcgr_dir ../pcgr-0.9.2/ --output_dir Test/ --genome_assembly grch37 --sample_id 008108943_37 --input_vcf VCF/008108943.vcf --no_vcf_validate

2021-09-16 17:36:21 - pcgr-summarise - INFO - PCGR - STEP 3: Cancer gene annotations with pcgr-summarise
[W::vcf_parse] INFO 'FR' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'PRECISE' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'SVTYPE' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'END' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'LEN' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'NUMTILES' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'SD' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CDF_MAPD' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'REF_CN' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CI' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'RAW_CN' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'FUNC' is not defined in the header, assuming Type=String
Traceback (most recent call last):
  File "/pcgr/pcgr_summarise.py", line 206, in <module>
    if __name__=="__main__": __main__()
  File "/pcgr/pcgr_summarise.py", line 34, in __main__
    extend_vcf_annotations(args.vcf_file, args.pcgr_db_dir, logger, args.pon_annotation, args.regulatory_annotation, args.cpsr)
  File "/pcgr/pcgr_summarise.py", line 189, in extend_vcf_annotations
    w.write_record(rec)
  File "cyvcf2/cyvcf2.pyx", line 2364, in cyvcf2.cyvcf2.Writer.write_record
Exception: variant to be written has errorcode: 2

**Comment by sigven** [comment]
Hi again,

I briefly looked at your VCF, and it contains a lot of different entries not intended for use in PCGR, and I strongly suspect that this is why it fails during PCGR processing. Also, if you run it without the `no_vcf_validate` argument I am pretty confident the validator will complain, right? 

Importantly, keep in mind that the input VCF to PCGR should contain only SNVs/InDels (from what I can see your VCF contains structural variants, copy number variants etc., this is not intended for this type of PCGR input). Also, you [should avoid multi-allelic variants](https://pcgr.readthedocs.io/en/latest/getting_started.html#step-3-input-preprocessing), i.e. through decomposition of your VCF variant entries. Furthermore, in order to get the most out of PCGR you should also know which tags in the INFO column that denotes variant sequencing depth and variant allelic fraction, which can be fed as arguments to PCGR.  I also noticed some peculiar entries for which all variants (for a multi-allelic entry, `chr2    178098804       COSM1009929;COSM5437128;COSM717624`) were recorded with zero allelic fractions (i.e. AF=0,0,0), how do you consider these as valid variants? All in all, I cannot stress the importance of "cleaning" the input VCF and understanding the contents of it. Please have a look at the [example VCF files](https://github.com/sigven/pcgr/tree/master/examples) to look how they should be formatted for use in PCGR.

best,
Sigve

**Comment by mano2991** [comment]
@sigven i understand my vfc is not proper, i will check and let you know. thanks for your reply
