### ISSUE TITLE
Feature request: AF/DP presets

### ISSUE THREAD

**Issue by ohofmann** [sigven/pcgr#18]
Sigve,

@vladsaveliev got the AF/DP visualisation to work and it's positively making our life easier over here. Thanks again! Two questions came up:

1. Would it be possible to have text input boxes in addition to the sliders? We have cases with excessive sequencing depth making the DP slider jump straight from 0 to 60 read coverage. Being able to configure a range of AF/DP values to select from (to set a cap at coverage) would be a neat alternative.

2. By default we are likely to focus on variants in a certain AF and DP range. Would t be possible to preset those as start/end points for the sliders in the TOML file?

Best, Oliver

**Comment by sigven** [comment]
Hi Oliver,

I think i see your point here. The sliders are not very sensitive when there is excessive depth (we have experience the same). I think dropdown menus with pre-selected AF/DP values should work equally fine (i am thinking the DP could be implemented as list of "DP greater than X", while AF could have a list of min/max values?). I need to play a bit, and show you a demo so that you can have look before it goes into a release, OK? Btw, is there any specific DP/AF ranges that you would deem relevant as default for such a thing?

Sigve

**Comment by ohofmann** [comment]
DP greater than X would work (I still like being able to see the range of coverage). As a starting point we go for DP of 20 and AF >= 0.1, but that varies a lot between WGS, panel and other approaches.

**Comment by sigven** [comment]
AF/DP presets in 0.6.0 (configuration file)
