### ISSUE TITLE
PCGR 0.10.15 error

### ISSUE THREAD

**Issue by tinavisnovska** [sigven/pcgr#180]
- PCGR v0.10.15
- genome build: grch38 
- command: 
singularity exec --cleanenv -B /home/tina/work/sigve /home/tina/work/sigve/cpsr_pcgr_0.10.15/cpsr_pcgr_0.10.15_singularity_3.5.2.sif  pcgr --pcgr_dir ~/work/sigve/cpsr_pcgr_0.10.15/ --output_dir ~/work/sigve/test_cpsr_pcgr_0.10.15_out/singularity --sample_id CL-ArcoMetrix --tumor_dp_tag TDP --tumor_af_tag TVAF --call_conf_tag TAL --genome_assembly grch38 --input_vcf ~/work/sigve/test_cpsr_pcgr_in/CL-AcroMetrix_small_variants_all.vcf --include_trials --assay TARGETED --estimate_signatures --estimate_msi_status --estimate_tmb --no_vcf_validate --no_docker

- error message:
2022-02-09 18:47:32 - pcgr-writer - INFO - PCGR - STEP 4: Generation of output files - variant interpretation report for precision oncology
Traceback (most recent call last):
  File "/pcgr/bin/pcgr", line 10, in <module>
    sys.exit(cli())
  File "/pcgr/lib/python3.7/site-packages/pcgr/main.py", line 144, in cli
    run_pcgr(arg_dict, host_directories, config_options, DOCKER_IMAGE_VERSION)
  File "/pcgr/lib/python3.7/site-packages/pcgr/main.py", line 478, in run_pcgr
    rscript = utils.rscript_path(DOCKER_IMAGE_VERSION)
  File "/pcgr/lib/python3.7/site-packages/pcgr/utils.py", line 34, in rscript_path
    prefix = conda_env_path('pcgrr', docker_run)
  File "/pcgr/lib/python3.7/site-packages/pcgr/utils.py", line 50, in conda_env_path
    envdir = os.path.dirname(cp)
  File "/pcgr/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by tinavisnovska** [comment]
ok, I think this is an issue on my side ;)

**Comment by tinavisnovska** [comment]
Indeed, the problem was on my side, I was missing CONDA_PREFIX variable in my singularity image and the issue got resolved after defining the variable properly.

However, I'll mention here one more thing. The way the CONDA_PREFIX is processed by the conda_env_path function in pcgr/utils.py is sensitive to whether there is '/' at the end of CONDA_PREFIX or not - For example, consider CONDA_PREFIX to be '/a/b/c' or '/a/b/c/' - the character strings can be used interchangeably when used as paths, but envdir variable will be assigned '/a/b' or '/a/b/c' respectively and that can be causing some troubles when identifying env paths.

Anyway, this can be closed;)

**Comment by pdiakumis** [comment]
Oh that's a good catch @tinavisnovska, thanks for raising it!

```
>>> cp1 = '/dir/conda'
>>> cp2 = '/dir/conda/'
>>> os.path.dirname(cp1)
'/dir'
>>> os.path.dirname(cp2)
'/dir/conda'
```

I'll push a fix for next release. Keep this issue open please :-)

**Comment by tinavisnovska** [comment]
It works in the sense that the produced paths are the same. However, maybe the aim here is to get '/dir/conda' as the intended output.

So maybe something like this would suit better:

```
>>> cp1 = '/dir/conda'
>>> cp2 = '/dir/conda/'
>>> os.path.dirname(os.path.normpath(cp1)+'/')
'/dir/conda'
>>> os.path.dirname(os.path.normpath(cp2)+'/')
'/dir/conda'
```

**Comment by pdiakumis** [comment]
Oh dear, of course, thanks Tina! I think I need to comment more on what the code is _supposed_ to do :-)
Might need to think about a different way of doing this - I'm not too keen on specifying a trailing `/` like that.

**Comment by tinavisnovska** [comment]
Sure thing. Yeah, I believe there is a nicer way to incorporate the trailing `\`s into the code, just could not find one yet ;)

**Comment by pdiakumis** [comment]
Hi Tina,
I _think_ the code is actually (to my surprise!) doing the right thing. What we want `conda_env_path` to do is output `/path/to/conda/envs/{env}`, where `{env}` is `pcgr` or `pcgrr`. The `normpath` below takes care of potential trailing `/` in `CONDA_PREFIX`.

```
(conda_env_path function)


cp = os.path.normpath(os.environ.get('CONDA_PREFIX'))  # /path/to/conda/envs/FOO
env_dir = os.path.dirname(cp)                          # /path/to/conda/envs
env_path = os.path.join(env_dir, env)                  # /path/to/conda/envs/{env}
```

The `conda_env_path` function is basically used as a prefix to grab full paths to scripts in `conda/envs/pcgr/bin/` (or `conda/envs/pcgrr/bin/`), e.g. `conda/envs/pcgrr/bin/Rscript`, `conda/envs/pcgr/bin/pcgrr.R` etc.
Let me know if that makes sense! I've added some comments (and refactored the `utils.py` a bit in #182.

**Comment by tinavisnovska** [comment]
Hi Peter, 

what you write makes a lot of sense to me now, thanks for explaining. 

Apparently value of `CONDA_PREFIX` is set to `/path/to/conda` when base is active and changes to `/path/to/conda/envs/ENV` with `conda activate ENV`. However singularity has (or had at least, maybe this got resolved over time without me realising) some issues with `conda init` and `conda activate` and so I am directly modifying `PATH` variable to have `/path/to/conda/envs/pcgr/bin` inthere. So I was defining `CONDA_PREFIX` manually based on what that value was on my local computer in base - and when that did not work, I've adjusted `CONDA_PREFIX` a bit more so that pcgr finally worked properly, but I did not really understood what the problem was. ;)

Saying all that, you assume that when people use pcgr in conda, they create an exclusive named environment for pcgr (and that is exactly what they are told in the install instructions so they should follow ;)). However, if they for whatever reason decide otherwise or their `conda activate` does not adjust `CONDA_PREFIX` properly, they will get stuck here. 

I know this is a corner case and fixable on the user's side, but maybe there is a way to make the `env_path` assignment more robust - checking if subfolder `envs` is present in the path, if not then adding it, if yes then removing the environment name at the end of the path. Anyway, this is up to you ;)

**Comment by pdiakumis** [comment]
Hi Tina,

I also realised today (after trying to figure out what your issue was) the same thing about `CONDA_PREFIX` in `base` vs. activated envs so thanks for that! I'll see what I can do with `env_path`.
I agree that this is not the most robust setup for cases like Singularity (which admittedly, I have never used), and I really do plan on changing the way the env handling/naming happens (trust me, I really don't like the hard-coded environment names I've used in the code). I'm also using PCGR in a different project with multiple conda envs so I totally get what you're saying with the env naming.

The main reason for the 'hacks' we're using to grab scripts from `pcgr` or `pcgrr` boils down to the version incompatibility of several conda packages (`ensembl-vep`, `cyvcf2`, `r-base` are the main ones) in Linux vs. Mac (e.g. `VEP` gets downgraded to something like v89 from 3+ years ago in order to play nicely with a non-ancient version of `cyvcf2` and `R` v4), so we decided to split the Python part into a separate pkg, and the R part in another.
We wanted to have everything in a single conda environment originally, but the dependencies just weren't playing nicely with each other (I literally spent days trying different combinations of dependency versions). Maybe these dependency graphs get solved in the near future so that will make the code a lot easier to maintain.

I'll close this issue but feel free to open another one.
Thanks again for testing, this is extremely valuable feedback!
