### ISSUE TITLE
'names' attribute [20] must be the same length as the vector [18]

### ISSUE THREAD

**Issue by YingYa** [sigven/pcgr#187]
Whenever you encounter an error, please also include:

- [v1.0.0] Version of PCGR.
- [grch38] Genome build (grch37/grch38).
- [/share/app/singularity/3.8.1/bin/singularity exec -e -B /share/app/PCGR/data-20220203:/data -B /share/user/workdir:/workdir /share/app/PCGR/pcgr-v1.0.0.sif /opt/mambaforge/envs/pcgr/bin/pcgr --input_vcf /workdir/Normal-VS-Tumor.vcf.gz --input_cna /workdir/Normal-VS-Tumor.seg.tsv --logr_gain 0.8 --logr_homdel -0.8 --cna_overlap_pct 50 --pcgr_dir /data --output_dir /workdir --genome_assembly grch38 --sample_id Tumor --vcfanno_n_proc 4 --vep_n_forks 4 --vep_regulatory --estimate_tmb --estimate_msi_status --estimate_signatures --all_reference_signatures --tumor_dp_tag TDP --tumor_af_tag TVAF --control_dp_tag NDP --control_af_tag NVAF --call_conf_tag TAL --tumor_site 9 --tumor_purity 0.33 --tumor_ploidy 2.4 --assay WGS --include_trials --force_overwrite --no_docker] the complete command you used to invoke pcgr (including all explicit options)
- [2022-03-06 15:48:51 - pcgr-report-generation - INFO - Number of SNVs for signature analysis: 27801
Error in names(color_vec) <- cols$group :
  'names' attribute [20] must be the same length as the vector [18]
Calls: <Anonymous> -> <Anonymous>
Execution halted] the **full** error message

Whenever possible, please also provide links to query VCF file.

**Additional context**

**Comment by sigven** [comment]
Hi @YingYa,
Thanks for reporting. I am aware of the issue, I have noted this in the code actually:
https://github.com/sigven/pcgr/blob/master/pcgrr/R/mutational_signatures.R#L161-L169

The issue arised since your signature analysis of your sample returned contributions from more than 18 different aetiologies (Aging, MMR deficiency, UV damage etc). I reckoned this to be a very rare scenario, but it obviously can happen :-). Before I fix the issue in the code, I suggest, as temporary fix for your sample, that you try the following:

1) skip the `--all_reference_signatures` option.
2) If you want more known signatures available for fitting, you can lower the threshold for known signatures attributed with `Colon` by setting i.e. the `--prevalence_reference_signatures` to 2 (percent). 

Let me know if that works for you.

best,
Sigve

**Comment by sigven** [comment]
Resolved in v1.0.1, see [CHANGELOG](https://sigven.github.io/pcgr/articles/CHANGELOG.html)
