### ISSUE TITLE
conda installation issue with ncurses too many levels of symbolic links

### ISSUE THREAD

**Issue by pdiakumis** [sigven/pcgr#213]
Reporting this conda installation issue we got via email:

```
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: failed
[Errno 40] Too many levels of symbolic links: '[...]/miniconda3/pkgs/ncurses-6.2-h58526e2_4/share/terminfo/N/NCR260VT300WPP'
```

It was reported in Nov2020 at https://github.com/conda/conda/issues/10333 and there are several workarounds, but maybe we can explore bumping ncurses from 6.2 to 6.3 in the pcgr conda env to accomodate our users.

**Comment by gitfourteen** [comment]
Change back miniconda3 installation directory to '/home/<user>/minicond3' is not a satisfied answer for me.
2 points:
1. when installing anaconda3 in WSL 2 Ubuntu 18.04 or 20.04, there is no such OSError.
2. we choose to install under a specified directory, eg., `/mnt/d/miniconda3`, because we would rather not eat up `c drive` capacity: `C:\Users\[USERNAME]\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_[CODE]\LocalState\rootfs\`

Until today, this bug of Miniconda still exits when one creates a new environment.
`OSError: [Errno 40] Too many levels of symbolic links: '/mnt/d/anaconda/pkgs/ncurses-6.4-h6a678d5_0/share/terminfo/n/ncr260vt300wpp'`
