### ISSUE TITLE
No-docker option

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/pcgr#35]
Since @zacshi is also interested, creating a new issue from [here](https://github.com/sigven/pcgr/issues/34#issuecomment-388759623) for possible discussion.

On our compute cluster, we can't install Docker, so we use a [modified PCGR fork](https://github.com/vladsaveliev/pcgr) that can work without one. 

Basically what we did, we walked through Sigve's Dockerfile and prepared a [conda file]([environment file](https://github.com/vladsaveliev/pcgr/blob/master/install_no_docker/conda_environment.yml)) with the dependencies. Some packages are not yet on conda (but shouldn't be a problem to add them), so we just installed them on top - the overall installer script looks like this:https://github.com/vladsaveliev/pcgr/blob/master/install_no_docker/install.sh

Then we modified `pcgr.py` to add a `--no-docker` option and generalized the code a bit to make it execute all sub-commands from either local or docker based on on that argument. We also had to add some minor things like an `output_dir` command line argument into some scripts.

I realise that the problem with the no-docker option is that there is no guarantee that all the dependencies will install and run smoothly on any machine, and I fully understand why Sigve wouldn't want to make this option official. Supporting all possible systems is really painful and there is no practical reason to spend time on that.

But I think it would be nice to have it as an _undocumented_ option, to be run on users's own risk. Actually, since most of the dependencies are available on conda (bioconda), they can be already installed under most linux systems and macos. Adding the remaining ones can make the PCGR environment almost cross-platform among unix-like systems, as conda attempts to guarantee it.

Will be happy to make any changes and create a pull request, if it makes sense. Feel free to close the issue or leave it open until have time to go back to this - there is no rush for us with that, we are happy to use the fork and keep syncing it with the master

Vlad

**Comment by sigven** [comment]
Hi Vlad,

I think this is a very valuable add-on to the existing functionality. Thanks for investing time and effort into this:-) The original idea was of course that the Docker technology should prevent the establishment of this in the first place (:-)), but I am the first to realize that Docker is not well supported across HPC systems (it's been a hazzle here as well). FYI there have also been some developments at my local institution to run the workflow using Singularity, but that has not been completed.

Although a lot of code would be duplicated, I think (as a start) and for the sake of simplicity, it could make sense to make a separate Python script for the `--no_docker` option, so that it can be more easily maintained by you, and that I can still focus on maintaining the main pcgr.py script. In the longer run, it would make more sense to have both options in the same script (as you have established already). Note that this was my initial thinking before I've had the chance of actually looking at how much change there is to the code in your "no-docker" version (if this is less than I expect, let me reconsider).

Sigve

**Comment by vladsaveliev** [comment]
I think I was too enthusiastic and made more changes than necessary. Most of that is just the code style, like the usage of os.path.join for path concatenation. Basically this [one commit](https://github.com/vladsaveliev/pcgr/commit/d6872f7142a07f40adb4de1e3ea89d95ed0117d8) contains the minimal required changes to make it optionally work without Docker; the rest of my commits are just minor fixes and refactoring, and adding of the installation scripts.

There still seem a lot of changes in that commit, but they are all basically just adding variables for currently hard-coded paths like `output_dir`, `data_dir`, etc, so we can use different values for docker and non-docker versions:

```
if docker:
      data_dir = '/data'
      outpur_dir = '/workdir/output'
      vep_dir = '/usr/local/share/vep/data'
      r_sciprts_dir = '/'
else:
      data_dir = '.'
      outpur_dir = host_directories['output_dir_host']
      vep_dir = vepdb_dir_host
      r_sciprts_dir = './src/'
```

I can try to clean to reduce the number of changes even further. Then we can think if we want a separate script or use a single one :)
