### ISSUE TITLE
Error in STEP4

### ISSUE THREAD

**Issue by akhtar4ever** [sigven/pcgr#39]
Hi Sigve,

Please guide me, since I am getting below error:

2018-06-08 11:03:52 - pcgr-writer - INFO - STEP 4: Generation of output files - variant interpretation report for precision oncology
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 138 elements
Calls: <Anonymous> -> <Anonymous> -> read.table -> scan
Execution halted

Let me know what I need to check in my vcf. 

Not sure if its an issue, but no other way to communicate to you.

Also one more query:
 if the chromosome representation is like chr6_ssto_hap7 or chr7_gl000195_random then below warning was flagged and tool exited.

WARNING: Chromosome 6_ssto_hap7 not found in annotation sources or synonyms on line 32084
WARNING: Chromosome 7_gl000195_random not found in annotation sources or synonyms on line 36609
Argument "7_gl000195_random" isn't numeric in numeric comparison (<=>) at /home/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Stats.pm line 745, <$fh> line 107869.
Argument "6_ssto_hap7" isn't numeric in numeric comparison (<=>) at /home/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Stats.pm line 745, <$fh> line 107869.
[E::hts_idx_push] chromosome blocks not continuous
tbx_index_build failed: /workdir/output/new.pcgr_ready.pcgr_vep.vcf.gz

So to avoid this error I removed these lines from vcf.

Let me know whats more appropriate step to annotate such vcf files.

Sorry for bugging you, thanks a lot in advance for your support/guidance.

Thanks
Aktar

**Comment by sigven** [comment]
Hi Aktar,

No problem! This is the correct place to file such problems. In order to assess your problems properly, I need to have a look at your input VCF's. Ideally also the configuration files that you are using. Would you care to share those with me (my email is at the bottom of the github page)?

best,
Sigve

**Comment by akhtar4ever** [comment]
Hi Sigve,

I emailed you the vcf and config file.

Did you get chance to check it anytime?

Thanks
Aktar

**Comment by sigven** [comment]
Hi, 

Yes, I have. I found two problems with your run, one related to your calls (input VCF) and one related to PCGR:

1) You are running in tumor-only mode, meaning that you do not have a control sample, and the calls are thus supposed to contain a mix of somatic mutations and germline variants. However, looking at your input VCF, the caller you have used seem to make germline calls only (UnifiedGenotyper), and is a caller (to my knowledge) that is not intended to identify somatic variants. The input variants will thus not make sense for PCGR, which is supposed to highlight (putative) somatic variants (i.e. after filtering of germline variants in tumor-only mode).

2) A couple of INFO tags in your VCF had `Type=Character`, which was not properly handled by PCGR (i.e a bug). I have fixed this so that it is not a problem in the upcoming release.

**Comment by akhtar4ever** [comment]
Hi Sigve,

One query...
Currently in pcgr we are annotating 1K and gnomAD polymorphisms ,is there any way we can add other polymorphism databases like EXAC_AF.

Usually in VEP we can annotate canonical info by using --canonical option as argument while running VEP. Can we somehow pass the same option in pcgr?

Thanks
Aktar

**Comment by sigven** [comment]
Hi Aktar,

Regarding ExAC versus gnomAD: to my knowledge ExAC is really a subset of gnomAD, so querying this additional database would not give you all that extra information (see also [about gnomAD](http://gnomad.broadinstitute.org/about)). Variant Effect Predictor (VEP), which PCGR is built upon, has performed the transition from ExAC to gnomAD as of v90 (https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html). Although it is not a big deal for me to also append ExAC frequencies, I do not see the great benefit of doing so.

Regarding VEP's `--canonical option`; it is already present when running VEP through PCGR, and it is an [INFO tag in the PCGR VCF output](http://pcgr.readthedocs.io/en/latest/output.html#vep-consequence-annotations). It is not however highlighted specifically in the HTML reports or in the TSV file. PCGR do use the `--pick` option in VEP when choosing the block of annotation pr. variant, which use the `--canonical` data [indirectly](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick)

regards,
Sigve

**Comment by adbeggs** [comment]
Hi @sigven - I too am getting this error. Have changed variant caller for a specific project to Pisces (https://github.com/Illumina/Pisces) and it crashes out with the error:

[E::hts_idx_push] chromosome blocks not continuous
tbx_index_build failed:


[testvcf.zip](https://github.com/sigven/pcgr/files/5289034/testvcf.zip)

**Comment by sigven** [comment]
Hi,

Thanks for reaching out. First, note that Your VCF does not adhere to the VCF standards - did not pass the vcf-validator, you should try to fix those errors first. However, turning off VCF validation, and compressing the VCF input (bgzip + tabix), I compiled reports with the following command, using the latest PCGR version in dev (Docker image `pcgr:dev`):

`/Users/sigven/research/docker/pcgr/pcgr.py --input_vcf /Users/sigven/research/docker/pcgr/piscesexample.vcf.gz --pcgr_dir /Users/sigven/research/docker/pcgr --output_dir /Users/sigven/research/docker/pcgr --genome_assembly grch38 --sample_id pisces --conf /Users/sigven/research/docker/pcgr/conf/pcgr.toml --tumor_site 9 --no_vcf_validate --force_overwrite`

Results available here:
https://www.dropbox.com/sh/a2e1dpkxhfo3y4z/AADZMJxW-tFm0jS2-tCISvIka?dl=0

regards,
Sigve
