### ISSUE TITLE
Variants missing in most recent release of data bundle (CIViC)

### ISSUE THREAD

**Issue by MrsLaviniaG** [sigven/pcgr#45]
Hi Sigve,

We have noticed two issues with variants of interest in PCGR.
The first was TERT (5:g.1295228G>A).  This variant was annotated as "non-coding mutation" (PCGR version 0.6.2.1).  However it is in CIViC (https://civicdb.org/events/genes/79/summary/variants/248/summary#variant). Looking at an older data bundle (pcgr.databundle.GRCh37.20171117.tar), it is listed as a CIViC mutation, but it is not present in the most recent data bundle.

The second was NF1 (17:g.29562710G>T).  This was annotated as Tier 4 (VUS).  However it is listed in ClinVar as pathogenic (https://www.ncbi.nlm.nih.gov/clinvar/variation/439986/).  We think this variant would be picked up correctly with your pcgr_predispose tool.  We have given this tool a test but there appears to be a critical file missing (phenotype_ontology_oncology.tsv), any assistance you can provide would be welcomed.

with thanks again for your work on this invaluable tool.

Lavinia.

**Comment by sigven** [comment]
Hi Lavinia,

Sorry for the extremely late response to this issue. 

Regarding the TERT promoter mutation: frankly, I have no good clue as to why it dissapeared in a bundle update. I can see it now in the bundle that is going with the next release ((20180910), so at least it will not be an issue in the upcoming release.

Regarding the NF1 variant: yes, it will be picked up with the soon-to-be released [Cancer Predisposition Sequencing Report](https://github.com/sigven/cpsr), which you should utilize for germline variant analysis. Note that the NF1 variant will not be picked up/highlighted by any means in PCGR, as this is a germline variant, and not associated with any evidence items for prognosis/diagnosis/drug sensitivity in CIViC. PCGR is strictly focusing on the somatic side of things, which people sometimes forget. 

If you feed your germline variants to CPSR, it will list variants in known cancer predisposition genes in your query VCF that coincide with 1) Pathogenic and likely pathogenic ClinVar variants (showing results for both cancer phenotypes and undefined/non-cancer phenotypes), and 2) Variants of uncertain significance, the latter which I have assigned and ranked according to a pathogenicity score, which constitutes the aggregate score from a number of ACMG criteria ([Richards et al., _Genet Med._, 2015](https://www.ncbi.nlm.nih.gov/pubmed/25741868)), also implemented in [Huang et al., _Cell_ ,2018](https://www.ncbi.nlm.nih.gov/pubmed/29625052).
I am also playing with the idea of adding a "clinical" coverage module to CPSR/PCGR (this will take a BAM file as input) so that users can investigate whether there was enough sequencing coverage tp call variants (as defined up-front) at known pathogenic locations. 

Currently, there is [an issue](https://hub.docker.com/r/ensemblorg/ensembl-vep/builds/) with VEP that delays things somewhat wrt a new release, waiting for a fix there.

best,
Sigve

**Comment by MrsLaviniaG** [comment]
Hi Sigve

Thanks so much for the reply, it is appreciated.  And thanks for the clarification with the germline variant.

with regards,

Lavinia.
