### ISSUE TITLE
Missed TSGs

### ISSUE THREAD

**Issue by MrsLaviniaG** [sigven/pcgr#48]
Hi Sigve,

We have picked up variants that were annotated as Tier 4 but should be Tier 3 (pcgr_acmg) as they are TSGs:

MGA - given a TSG role by CGI and OncoKB, missed as a TSG by PCGR (absent in TSGene)
STAG2 - given a TSG role by CGI and OncoKB, missed as a TSG by PCGR (absent in TSGene)

Is it possible to include the information from OncoKB in PCGR?, the usage terms look reasonable:
http://oncokb.org/#/terms

Many thanks,

Lavinia.

**Comment by sigven** [comment]
Hi Lavinia,

Thanks for pointing this out. I have been considering merging OncoKB into PCGR, but was not sure if the usage terms were reasonable. It basically has to do with the distribution of the PCGR data bundle, if that is permitted with the usage terms, I'll have a closer look at that. 

I do have a feeling though that the majority of clinical evidence items in OncoKB are also present in CIViC (correct me if i am wrong), but that it may carry other properties (regarding TSGs for instance, see below) that would be worthwhile looking into.

As hinted to, integration of an additional source for clinical evidence items needs to be done with care, i.e. avoid duplicated entries, and making sure that evidence levels are consistent with the existing ones in PCGR (CIViC, CGI). This requires a significant amount of work.

The information listed in PCGR has to rely on a limited set of knowledge sources. Currently, TSGs/proto-oncogenes are retrieved from TSgene, but as you have figured out, this may in some cases not always be consistent or up-to-date with other sources (I can ask the authors of TSgene if they are planning an update). STAG2 seemed like the most significant failure, as this is also listed in the Cancer Gene Census. I have been considering [The Network of Cancer Genes](http://ncg.kcl.ac.uk/query.php) as an alternative resource for this, as this appear more up-to-date (they also list a huge number of candidate genes). I guess what I am trying to say is that is not easy to establish a "true" set of such cancer genes, as there are many different sources, and knowing which are supported by multiple lines of evidence rather than based on computational predictions is not trivial (if you get my point). If you want to throw in an effort, that is warmly welcomed:-)

regards,
Sigve

**Comment by MrsLaviniaG** [comment]
Dear Sigve

Thanks so much for your prompt reply. I agree completely with all of your
comments. VICC are currently working on harmonizing annotation sources. I
will have another look at their efforts and see if they might assist with
your annotation efforts.

With regards

Lavinia.

**Comment by sigven** [comment]
Yes, I agree, that would be very beneficial to PCGR. And I am following the developments there. Currently, however, I believe CIViC is very comprehensive in itself, and also the most convenient solution in terms of accessibility (API etc).

regards,
Sigve

**Comment by sigven** [comment]
Dear Lavinia,
This looks quite powerful, taken that one can add a filter that removes some likely false positives:
http://bionlp.bcgsc.ca/cancermine/

It also assigns each tsgene/oncogene with an associated tumor type, which may also be useful.

Sigve

**Comment by MrsLaviniaG** [comment]
Dear Sigve,
Looks like an excellent option.
This is really great, thanks so much for following up with this information.

with regards,

Lavinia.
