### ISSUE TITLE
Packaging pcgrr separately

### ISSUE THREAD

**Issue by pdiakumis** [sigven/pcgr#51]
Sigve,
Thanks for this great tool. I'm just curious about the R package integrated within PCGR. Is there any drawback to packaging it separately within its own repo (e.g. `sigve/pcgrr` or `sigve/rpcgr`)? The function documentation and proper structure is already there. On the other hand, I'm not that familiar with the Docker setup so not sure if it plays nicer this way, and if it communicates with Python in other ways. I'd love to help set it up if you want? This would probably help us with our conda environments/AWS setups too.

Cheers - Peter

**Comment by sigven** [comment]
Peter,
Thanks a lot for your message. Originally I thought this was the best way to organize the code, and I guess in principle this might still work. However, the R package is currently so tightly integrated with what comes from the upstream PCGR pipeline (both in terms of software  i.e. VEP, vcfanno and custom Python code, and parts of the data bundle) that I did not find a lot of sense to make the `pcgrr` package as a stand-alone thing. Basically, in the majority of cases you need to have the fully annotated VCF (step 1,2,3) to be able to play with the reporting and additional analysis functions within `pcgrr`. I hope you have a better understanding for the underlying reason of the current setup. 

I am not particularly familiar with developing for the conda environment, so any contributions here are warmly welcome. Since PCGR is a combination of software and lots of data, I believe it differs somewhat from the standard conda elements, which I believe is mostly software only(?), but I maybe wrong here..

regards,
Sigve

**Comment by pdiakumis** [comment]
Sigve,
Thanks so much for your quick comment. I can completely understand your reasoning behind this (I too have an R pkg that basically works tightly with VCFs output by a single SV caller). I'll have a play with PCGR (and its no-docker version) a bit more on the side and see if we can come up with something that gives us a bit more flexibility. 

All the best - Peter
