### ISSUE TITLE
Discrepancy between the report and the content of the file cna_segments.tsv.gz

### ISSUE THREAD

**Issue by przemekl** [sigven/pcgr#68]
I have test file with two copy number segments:
Chromosome      Start   End     Segment_Mean
chr1    990001  995000  0.029327
chr6    78295001        78300000        -29.701210
Pcgr html raport contains deletion with LogR=-29.701
File cna_segments.tsv.gz contains only a few records relating to amplification with LogR=0.029327.
Amplification has been filtered correctly, but what happened to the deletion missing from the cna_segments file?
I use dockerized version 'dev' with hg38 reference.

**Comment by sigven** [comment]
Hi,

Thanks for reporting! I’ll have a look. Would it be possible to share your input data (segment file) and config?

Sigve

**Comment by przemekl** [comment]
Of course. I have written above the entire contents of the segment file. Config in the attachment.
[test.toml.gz](https://github.com/sigven/pcgr/files/2788659/test.toml.gz)

**Comment by sigven** [comment]
Note that the CNA segments written to file (TSV output) constitute the [set of segments that show overlap with gene transcripts](https://pcgr.readthedocs.io/en/latest/output.html#output-files-somatic-copy-number-aberrations). Currently, segments that do not overlap any transcript are simply omitted, and I believe this is the reason that you do not se any output for chr6. I can include these non-transcript-overlapping segments in the feature (appending NA's) in order to avoid any confusion, maybe?

**Comment by przemekl** [comment]
The problem is that this segment appears in the report (screenshot attached)
![chr6_78295001_78300000](https://user-images.githubusercontent.com/1319577/51773409-0bdfce00-20ef-11e9-9efd-a49abef01134.png)

**Comment by sigven** [comment]
That is how it is supposed to work. All filtered segments are shown in the report (and potential biomarkers). The TSV file output is transcript-focused, and will thus omit segments with no overlapping transcripts.
