### ISSUE TITLE
deconstructSig usage

### ISSUE THREAD

**Issue by ohofmann** [sigven/pcgr#7]
Hi,

done some more testing and seem to be running into odd mutational signatures that I did not expect. It seems that PCGR defaults to exome data (tri.counts.method = 'exome') which might be causing [problems with WGS results](https://github.com/raerose01/deconstructSigs/issues/2#issuecomment-214356002). Any chance of making this configurable?

Best, Oliver

**Comment by sigven** [comment]
Hi Oliver,
Very good point. This could be taken into account relatively easy, I am sure. A grant application is keeping me busy at the moment, so sorry for being a bit unresponsive. I will work with a new release asap, including support for allelic support etc.

best,
Sigve

**Comment by sigven** [comment]
Hi Oliver, 
Coming back to this matter. I am, as you, struggling a bit to understand which normalization would make sense for WES versus WGS, both from [your previous correspondence](https://github.com/raerose01/deconstructSigs/issues/2#issuecomment-214356002), and also from the documentation that goes with the deconstructSigs R package. According to the [package docs](https://cran.r-project.org/web/packages/deconstructSigs/deconstructSigs.pdf): " For exome data, the 'exome2genome' method is appropriate for the signatures included in this package. For whole genome data, use the 'default' method to obtain consistent results.". From the [deconstructSigs GitHub page](https://github.com/raerose01/deconstructSigs) it is however stated that "For exome data, the default method is appropriate for the signatures included in this package.". Have you been able to reach a conclusion/recommendation here, based on your comprehensive empirical testing? Also with respect to the number of mutations needed. In order to make it properly configurable within PCGR, it would be valuable with your input.

**Comment by ohofmann** [comment]
I actually haven’t — and didn’t spot that contradictory information Ouch.

We’ll be comparing the deconstructSig calls vs a set of around 300 PDACs in the next 2 months or so. Can provide an update at that point. Alternatively, new signatures are being presented just now at ICGG in Seoul which should be released in the next month; might make sense to wait for the next round of tools.

More in a bit, Oliver



--
@fiamh
Skype: ohofmann
+61 466 366 501

**Comment by sigven** [comment]
Thanks, at least I'll notifiy the deconstructSigs authors about the contradictory info.

**Comment by sigven** [comment]
Analysis of mutational signatures in PCGR 0.4.0 is made more configurable (user can specify trimer normalization and number of signatures in search space)
