### ISSUE TITLE
Variant are filtered out in tumor only mode even if the pop frequency is low

### ISSUE THREAD

**Issue by apastore** [sigven/pcgr#71]
Hi sigven, thanks for this package. I am tring to understand why some variant are filtered out even if the Allelele frequencies are low. 
Here is an example. In case you need a vcf file I can send you separatelly 
https://gnomad.broadinstitute.org/variant/13-28601361-A-G

Thanks a lot!
Alessandro

**Comment by sigven** [comment]
Dear Alessandro,

Here is my current thinking, not considering your input data or configuration for now. 

The variant you are referring to should not be filtered if the MAF threshold is set to the default (0.01). However, there is an additional option in the TOML file that also removes(filters) putative germline variants due to their presence in the dbSNP database (`exclude_dbsnp_nonclinical = true`). The variant referred to above is present in dbSNP (and is not seen in TCGA, which would indicate it as an somatic event), and would thus be filtered out in tumor-only mode. 

Bottomline, as a start I suggest that if you want to consider such very low-frequency variants as likely somatic events, try setting `exclude_dbsnp_nonclinical = false`.

best,
Sigve

**Comment by apastore** [comment]
Yes this is definitely a good point! I misunderstood the filter criteria. And definitely I want to keep that variant since is reported as functional. 
Thanks!
